version: '3'
networks:
  my-network:
    driver: bridge

services:
  my-mysql:
    image: mysql:latest
    hostname: mysql
    networks:
      - my-network
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_USER: 'flashcard'
      MYSQL_PASSWORD: '123456'
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    expose:
      - '3306'

  flashcard:
    image: hfteam/ubuntu-flash:latest
    networks:
      - my-network
    container_name: flashcard
    command: tail -f /dev/null
    volumes:
      - ../code/:/home/flashcard
    ports:
      - '3000:3000'
